### PR TITLE
Basic implementation of jinja2 templating

### PR DESCRIPTION
**Pull request by rkdarst**
Initial attempt at jinja2 templates.  Backwards compatible and works for me, but needs documentation and a bit more before finalizing.  Is this wanted?

- If the batch_script or any other string has {{ or {% in it, treat it
  as a jinja2 template and do advanced formatting.
- Allows for optional options to be more easily supported.
- Initial implementation for SlurmSpawner only.

Also solves #64.

### CODE REVIEW

**Comment by rkdarst** [comment]
Updated with some basic documentation.

It's turning out that a lot of my other changes are somehow depending on this - is there any chance this can be accepted soon?  Anything else that I can do to fix it up?

**Comment by rkdarst** [comment]
My suggested order of pulling:
- #66  (this)
- #74 (slurm script improvements)
- #72 (may require minor conflict resolution, touch different but nearby lines)
- #73 (requires rebase)
- Changelogs will come later, since they will all conflict

I hope there are no major incompatibilites between them, but I will do more testing as things proceed.  If someone would comment on the requests (what will be accepted and not), then I can integrate myself, test, and make new PRs.  All are individually and in certain combinations tested on my test jupyterhub deployment over several days.

It would help a lot to do true merges so that I can most easily keep rebasing things.

If there is anything further I can do, or ways I can better coordinate, please let me know.

**Comment by mbmilligan** [comment]
Hi, thanks for this work! Now that we've issued the current release I think we're ready to start moving on this. I would like to adjust your proposed order, though. In my mind, PR #72 should go first, because that enables us to write tests of the form:

```python
def test_torque()
  expected_submit_cmd = "qsub blah blah"
  expected_submit_script = "#PBS foo bar ..."
  class TestTorque(TorqueSpawner):
    def run_command(...)
        assert command_and_script_match_expectations()

  spawner = TestTorque(args)
```

I would definitely feel more comfortable starting in on the templating changes if we can write tests to confirm that we aren't changing the generated commands and scripts in unexpected ways. Let me know if you have thoughts about that plan.

**Comment by rkdarst** [comment]
I'm wondering what the status of all of my PRs is.  I'd rather integrate using upstream instead of in my own repo, so that I can get feedback and solve problems it goes along, instead of having one giant PR with everything.  I'd like to move fast, to test with jupyterhub 0.9 and generally not lose my momentum now.

If you'd like help with with batchspawner overall, I'm happy to do whatever I can.

**Comment by mbmilligan** [comment]
Hi, thanks for checking in!

As I mentioned in my previous comment, I think the desired order of operations is to 

1. Merge PR #72 
2. Write some tests using that functionality that confirm integrity of the generated commands/scripts
3. Merge the templating changes, using the new tests to verify correctness

The difficulty I ran into is that if we merge these PRs into master, it becomes somewhat difficult to back out if one of the individual PR branches needs additional work. However, to keep things relatively easy to reason about, I do agree with keeping these functionality changes in separate feature branches. I think the correct way forward is to create an integration branch off of master that will receive these PRs. In case of conflicts we can then rebase the PRs against that branch as it develops, and once finished the integration branch would merge into master or a release prep branch. Doing it that way, we'll get testing reports at each step along the way, but still be able to back out, or even regenerate the integration branch from scratch, if needed.

So to begin, I'll create the integration branch and pull #72 into it, then we can figure out testing and move on with the rest.

**Pull request merged**
