### PR TITLE
Integration: #143 (inc. #141, #139), #130, #86, #90

### PR DESCRIPTION
**Pull request by rkdarst**
This is an integration branch made to test if the most important other
PRs work together, while waiting for others to go in.  However it can
be seen as a line of development, too.

All of these PRs do work together, it seems, with only minor fixups.
This could use testing on other clusters.

- #140: JH1.0 compatibility, most others wait for this.
- #130: minor documentation
- #90: refactor to use Python 3.5 asyncio
- #86: JH0.9 progress indicators

Closes: #143, #141, #139, #133, #130, #90, #86 (PRs)
Closes: #131, #126 (Issues) at least.

### CODE REVIEW

**Comment by mbmilligan** [comment]
Ok @rkdarst - I see the tests have been passing for a while now on this integration branch, and it's accumulated a pretty good number of changes. Do we know if a human has actually tried using this branch to confirm end-to-end functionality? In the interest of moving things forward, I'd like to start merging from these integration branches rather than potentially duplicating your efforts by merging individual PRs.

**Comment by rkdarst** [comment]
I generally test these on my dev setup as I'm working on them.  In this branch's case, I tested yesterday and was just about to make it live.  I guess there will be news on that in the next day or two.

**Comment by rkdarst** [comment]
I've made this live on my cluster, and it is working as expected.

**Comment by mbmilligan** [comment]
Great to hear it! In the absence of others chiming in, I think that's good enough for me. Merging.

**Pull request merged**
