### PR TITLE
Add req_condaenv to BatchSpawnerBase

### PR DESCRIPTION
**Pull request by TerenceLiu98**
Specify the `conda` environment or `python` environment with `req_condaenv` in [BatchSpawnerBase](https://github.com/jupyterhub/batchspawner/blob/1decdf259a25c8e33e90de7a5817da11a92c0326/batchspawner/batchspawner.py#L66)

### CODE REVIEW

**Comment by rcthomas** [comment]
Hi @TerenceLiu98 can you give an example of how this is used?

**Comment by TerenceLiu98** [comment]
@rcthomas Here is am example:

```python
c.SlurmSpawner.batch_script = '''#!/bin/bash
#SBATCH --chdir={homedir}
#SBATCH --output={homedir}/jlab_slurmspawner_%j.log
#SBATCH --partition={partition}
#SBATCH --time={runtime}
#SBATCH --cpus-per-task={nprocs}
#SBATCH --mem={memory}
#SBATCH --gres={gres}
#SBATCH --job-name=jlab-spawner

module anaconda/5.3.1
conda activate {condaenv}
{cmd}
'''

c.ProfilesSpawner.profiles = [
     ('GPU Node with PyTorch-1.9.0', 'GPU-Node', 'batchspawner.SlurmSpawner', dict(req_partition='GPU-Node', req_nprocs='4', req_runtime='01:00:00', req_memory='8192M', req_gres="gpu:teslaV100:1", req_condaenv="PyTorch")),
     ('GPU Node with Tensorflow-2.5.0', 'GPU-Node', 'batchspawner.SlurmSpawner', dict(req_partition='GPU-Node', req_nprocs='4', req_runtime='01:00:00', req_memory='8192M', req_gres="gpu:testlaV100:1", req_condaenv="Tensorflow-GPU")),
]
```

And, this is suitable for the shared environment.

**Comment by TerenceLiu98** [comment]
Actually, I am now facing #217 and I don't know what to do :(
But I am sure it is not caused by `req_condaenv`

**Comment by mbmilligan** [comment]
Hi, I am going to close this old issue. For the benefit of future people searching for this, I would note, there is a `req_prologue` variable already: 

    req_prologue = Unicode(
        "",
        help="Script to run before single user server starts.",
    ).tag(config=True)

You could activate a conda or venv environment by inserting the appropriate command there.

**Pull request closed without merging**
