### PR TITLE
Add a changelog to bottom of README.md

### PR DESCRIPTION
**Pull request by rkdarst**
This changelog includes changes going back one year only.  It includes two more changes for which I have PRs since they are not major changes, but they can also be removed if they aren't accepted.

It could use advice on upgrading, but I don't see any breaking changes.

Feel free to just copy this info to a different file and close the PR, too.

### CODE REVIEW

**Comment by mbmilligan** [comment]
Many thanks, this is one of the last things holding up tagging the release!

**Comment by mbmilligan** [comment]
Oh and FYI, I'll accept the `--uid` patch, but the templating change will wait until after the release. But now that we've gotten the project hammered into much better shape, I'm certain releases will come more regularly after this!

**Comment by rkdarst** [comment]
Thanks!  Not sure if you can re-open the PR, but I've pushed an update to the branch removing the mention of templates.

**Comment by mbmilligan** [comment]
I could, but don't worry about it, I'm running through making various
tweaks now.

**Pull request merged**
