### PR TITLE
Adding PBSSpawner

### LINKED ISSUE #79: Batchspawner and PBS Pro 14.1.0
Hi,

Does anybody know if the TORQUE spawner is compatible with PBS Pro 14.1.0?
The basic syntax is pretty similar (if not identical).

Has anybody had success with it?

Thanks

### PR DESCRIPTION
**Pull request by guillaumeeb**
For PBS versions above > 13.X.
Closes #79 

It works on my environment with the following config:
````python
c.BatchSpawnerBase.req_prologue = 'module load conda; source activate jupyterhub'
c.BatchSpawnerBase.exec_prefix = 'sudo -E -u {username} env PATH=$PATH'
````

First line for loading correct env for the user. Second line because the PATH does not contain qsub and other PBS methods when sudoing.

### CODE REVIEW

**Comment by guillaumeeb** [comment]
Not quite sure what to do with the failures here...

**Comment by rkdarst** [comment]
Would you call this ready to go?  Does it work in your local tests and can you keep improving where needed?

Can I add your github username as a maintainer in the new spawner description in `SPAWNERS.md` which I am preparing?  This might mean you are occasionally notified about upgrades/tests which needs to be done to all spawners.

**Comment by guillaumeeb** [comment]
Yes it is good for me, I currently use this code for our jupyterhub instance, it works well. Sorry I did not make it clear it is ready for reviews.

No problem adding my username to the maintainer!

There is the problem of travis build though, but you may know something about this.

**Comment by guillaumeeb** [comment]
Thanks, let me know if something is needed from me!

**Pull request merged**
