### PR TITLE
Replace use of scripts with entry_points

### LINKED ISSUE #235: Replace `scripts` with `console_scripts`
### Proposed change

While this package _doesn't_ require being entirely cross-platform, use of `scripts` is more portable and better managed on different downstreams.

### Alternative options

Keep using scripts.

### Who would use this feature?

Downstream packagers, such as `conda-forge` can reason 

### (Optional): Suggest a solution

Likely, need to 
- replace
  - `scripts="scripts=glob(pjoin("scripts", "*"))` with
  - `entry_points=dict(console_scripts=["batchspawner-singleuser=batchspawner.singleuser:main"])`
- delete `scripts/` (and any references in other files, etc)

### PR DESCRIPTION
**Pull request by bollwyvl**
## References

- fixes #235

## Changes
- [x] replaces use of `scripts` with `entry_points: console_scripts`
  - this generally generates better/more secure scripts that are more predictable for downstream packagers e.g. debian, conda-forge
  - also more cross-platform-compatible, which is a story for another day...

### CODE REVIEW

**Review by consideRatio — APPROVED** [review]
This looks good to me, but I'm not so confident on this technically etc so I'll ping someone else for review as well.

@minrk and @rkdarst I saw that this project isn't getting so much maintainer attention and hoped to ensure a few simpler PRs at least got some attention. As I'm not an active user myself so I only dare merge things that seems very clear to not break something, perhaps you could have a look at this small PR?

**Comment by bollwyvl** [comment]
Here's the corresponding PR on jupyterhub itself:

https://github.com/jupyterhub/jupyterhub/pull/2313

**Comment by consideRatio** [comment]
Nice that makes me quite confident this is good to go, I'll go for a merge if this grows stale.

Btw, test failures are unrelated and fixed by #241.

**Comment by consideRatio** [comment]
Given that this pattern was demonstrated sensible in jupyterhub without other changes needed, I'll go for a merge on this now that also all tests has passed by fixing it in other PRs.

**Pull request merged**
